### ISSUE TITLE
PA: REVIEW Tasks

### ISSUE THREAD

**Issue by stellashen** [stellashen/cross-off#10]
- [x] Users can add a new task
- [x] Each task has a checkbox before its title
- [x] Users can set due dates and save the task to a list
- [x] Users can edit a task
- [x] Users can delete a task
- [x] Users can cross off a task when completed
- [x] Completed tasks will be moved to the "completed" list automatically upon completion
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Seeded with info to demonstrate this feature

**Comment by wongshington** [comment]
this looks great!
- [ ] on the task form page, i think the placeholder text and some of the other gray borders are a little difficult to read because the background is also gray

**Comment by stellashen** [comment]
Thanks! Changed that to a darker shade.
