### ISSUE TITLE
PA: REVIEW User Auth

### ISSUE THREAD

**Issue by stellashen** [stellashen/cross-off#8]
- [x] New account creation, login, logout
- [x] guest/demo login
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Seeded with info to demonstrate this feature

[CrossOff Heroku Site](https://cross-off-app.herokuapp.com)

**Comment by wongshington** [comment]
This looks so good!!!
just a few more things and i can check it off
- [ ] errors clear from form to form 
     -if i enter the wrong log in information but then switch to the signup form, the errors for "Invalid email or password" should be cleared
- [ ] put a space between Nickname and (optional) so it doesn't look as scrunched together
- [ ] your site is CrossOff, but the title for the tab shows it as two words "Cross Off"
- [ ] center the "back to homepage" link in the middle of the form 
    - maybe have it capitalized to say "Back to Homepage" (up to you if you want to or not)
    - same thing with the link to the "Sign in" form, should capitalize to "Sign In"

**Comment by wongshington** [comment]
Everything looks great!
